# LISTA DE PANDAS-2

**Importe as bibliotecas necessárias**

**Importe os dados sobre as ações, que estão nos arquivos "carteira.csv" e "ativos.csv".**

In [54]:
##### SEU CODIGO COMECA AQUI #####

import pandas as pd

carteiras = pd.read_csv("carteiras.csv")
ativos = pd.read_csv("ativos.csv")
ativos

,data,BPAC5,RAPT4,CMIG4,MELK3,DIRR3,PLPL3,BPAN4,BRAP4,27.635.189/0001-45,...,ITUB3,AURE3,WEGE3,BRPR3,HBSA3,EVEN3,UGPA3,NEOE3,TCSA3,ELET3
0,2021-12-31,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.0,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
1,2022-01-03,96.153846,99.080037,98.245614,99.487179,95.594020,95.692308,95.786517,98.639456,100.0,...,101.613068,100.000000,97.089145,96.853625,98.260870,95.902883,97.111417,97.839506,94.182825,97.665370
2,2022-01-04,94.423077,97.884085,98.169336,98.974359,92.210858,93.846154,88.295880,99.559824,100.0,...,103.867641,100.000000,96.604002,94.254446,90.144928,94.385432,93.466300,96.234568,89.196676,95.570189
3,2022-01-05,86.730769,94.388224,95.041953,97.179487,85.995279,86.461538,88.576779,99.799920,100.0,...,101.770364,100.000000,91.510006,89.740082,85.217391,89.984825,90.990371,94.382716,81.994460,95.181084
4,2022-01-06,84.574684,95.676173,92.982456,95.641026,84.107002,84.923077,89.513109,102.641056,100.0,...,103.605481,100.000000,91.479685,89.056088,83.768116,90.743551,89.683631,93.273261,74.792244,95.031428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,2022-07-25,100.517499,95.537109,114.691627,100.249730,89.613702,75.555017,63.874883,95.708112,NaN,...,106.765198,88.046662,81.486868,116.000672,61.449275,70.561457,91.799236,96.090960,62.880886,136.756247
142,2022-07-26,98.573253,95.731488,113.419631,99.191685,88.301882,74.903681,60.117537,95.581234,NaN,...,106.237963,88.353659,80.625224,116.000672,61.739130,72.534143,89.287138,96.479992,60.110803,136.146409
143,2022-07-27,100.517499,98.161221,119.355612,103.159352,91.663421,77.509027,60.493271,95.496649,NaN,...,106.132516,88.108061,82.687014,120.153441,64.347826,75.720789,92.516978,99.203217,63.434903,138.341827
144,2022-07-28,100.906348,98.452789,118.719614,105.010930,95.516892,81.417045,61.432608,96.765426,NaN,...,106.765198,85.959084,85.948951,120.015015,66.376812,80.273141,91.655688,97.387734,67.313019,138.585762
145,2022-07-29,103.628292,97.675274,119.143613,104.746419,97.074678,79.137367,62.371944,95.073723,NaN,...,106.923369,87.125672,86.287453,116.554374,64.637681,81.031866,91.081494,96.026121,65.650970,139.683471

**Exercício 1: Filtragem de dados**

Filtre o Dataframe a partir de 5 ações, de modo que essas ações podem ser escolhidas pela sua preferência ou de forma aleatória. Após a filtragem, salve em uma nova variável.

In [61]:
##### SEU CODIGO COMECA AQUI #####


acoes = ["ITUB3", "WEGE3", "ELET3", "BPAN4", "TCSA3"]
acoes = ativos[acoes]

acoes

          ITUB3       WEGE3       ELET3       BPAN4       TCSA3
0    100.000000  100.000000  100.000000  100.000000  100.000000
1    101.613068   97.089145   97.665370   95.786517   94.182825
2    103.867641   96.604002   95.570189   88.295880   89.196676
3    101.770364   91.510006   95.181084   88.576779   81.994460
4    103.605481   91.479685   95.031428   89.513109   74.792244
..          ...         ...         ...         ...         ...
141  106.765198   81.486868  136.756247   63.874883   62.880886
142  106.237963   80.625224  136.146409   60.117537   60.110803
143  106.132516   82.687014  138.341827   60.493271   63.434903
144  106.765198   85.948951  138.585762   61.432608   67.313019
145  106.923369   86.287453  139.683471   62.371944   65.650970

[146 rows x 5 columns]

**Exercício 2: Retorno**

Utilizando o Dataframe filtrado no exercício anterior, calcule o retorno diário dessas 5 ações. Para isso, utilize o método `pct_change`. Além disso, mude o nome das colunas para o nome da ação seguido de uma hashtag, por exemplo, 'BBAS3#'.

salve um uma variável chamada `retorno`.

In [66]:
##### SEU CODIGO COMECA AQUI #####

acoes = acoes.rename(columns={"ITUB3" : "ITUB3#", "WEGE3" : "WEGE3#", "ELET3" : "ELET3#" , "BPAN4" : "BPAN4#", "TCSA3" : "TCSA3#"})

retorno = acoes.pct_change()

retorno

       ITUB3#    WEGE3#    ELET3#    BPAN4#    TCSA3#
0         NaN       NaN       NaN       NaN       NaN
1    0.016131 -0.029109 -0.023346 -0.042135 -0.058172
2    0.022188 -0.004997 -0.021453 -0.078201 -0.052941
3   -0.020192 -0.052731 -0.004071  0.003181 -0.080745
4    0.018032 -0.000331 -0.001572  0.010571 -0.087838
..        ...       ...       ...       ...       ...
141  0.013514  0.030027  0.004929 -0.039548 -0.034043
142 -0.004938 -0.010574 -0.004459 -0.058824 -0.044053
143 -0.000993  0.025573  0.016125  0.006250  0.055300
144  0.005961  0.039449  0.001763  0.015528  0.061135
145  0.001481  0.003938  0.007921  0.015291 -0.024691

[146 rows x 5 columns]

**Exercício 3: Ordenar**

Utilizando o método `describe`, analise a média de retorno das ações. Após isso, organize os dados de tal modo que as ações sejam apresentadas de forma decrescente, isto é, a ação que teve a maior média de retorno para a  ação que teve a menor média de retorno.

  
   *Lembre-se de definir o parâmetro 'ascending' e 'by'.*

In [103]:
##### SEU CODIGO COMECA AQUI #####

retorno.describe()

media_retorno = retorno.mean()

maior_retorno = media_retorno.sort_values(ascending=False)

maior_retorno

ELET3#    0.002540
ITUB3#    0.000571
WEGE3#   -0.000715
TCSA3#   -0.002097
BPAN4#   -0.002700
dtype: float64

**Exercício 4: Manipulação** 

Para a ação que obteve a maior média de retonos no périodo apresentado, crie uma coluna chamada `acima_da_media_x`, sendo o 'x' o nome da ação. Sendo assim, essa coluna deve conter valores booleanos, `True` caso a ação esteja com o preço acima da sua média e `False` caso o preço da ação seja menor ou igual a média. Feito isso, printe apenas os dados que são iguais a `True`. 

*Dessa forma, poderemos saber em quais dias que a ação obteve um retorno maior que a sua média*

In [ ]:
##### SEU CODIGO COMECA AQUI #####

**Exercício 5: Proporção**

Após descobrir em quais dias que a ação teve um retorno maior que a sua média, calcule qual foi a proporção em que isso aconteceu, ou seja, a proporção de dias que esteve acima da média em relação ao total de dias.

*printe essa proporção da seguinte forma: 'A proporção de dias acima da média foi de X%', sendo 'X' a proporção. Arredonde em duas casa decimais o valor encontrado*

In [ ]:
##### SEU CODIGO COMECA AQUI #####
acima_da_media = df[df["retornos"] > np.mean(df["retornos"])]
prop = len(acima_da_media)/len(df["retornos"])

**Exercício 6: Junção**

Por fim, faça a união **total** do dataframe contendo cinco primeiras ações escolhidas  inicialmente (no ex. 1) com o dataframe contendo os retornos dessas ações (criado no ex.2). Espera-se um único dataframe como resposta.

In [ ]:
##### SEU CODIGO COMECA AQUI #####
lista = [1,2,3,7,8]
acima = lista[lista > mean(lista)]
prop = len(acima)/len(lista)
print(prop)